name: Scrivi Hello World ogni 5 minuti

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Esegui scrivi_hello.py
        run: python scrivi_hello.py

      - name: Configura Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit e push di output.txt
        run: |
          git add output.txt
          git commit -m "Aggiornato output.txt automaticamente"
          git push
